import Carousel from "@/components/Home/Carousel";
import Section from "@/components/Home/Section";
import React from "react";
import "tailwindcss/tailwind.css";
import Head from "next/head";
import axios from "axios";

export default function Home({posts}) {
  console.log(posts)
  return (
    <div className="">
      <Head>
        <title>EC BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />  
      </Head>
      <>
      <Carousel />
      <Section posts={posts} />
      </>
      
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const { req, params } = context;

  
  const posts = await axios.get(`${process.env.NEXT_PUBLIC_url}content`);

  return {
    props: {

      posts : posts ? posts.data : null,
    },
  };
};

