import Carousel from "@/components/Home/Carousel";
import Section from "@/components/Home/Section";
import React from "react";
import "tailwindcss/tailwind.css";
import Head from "next/head";
import axios from "axios";

export default function Home({posts,populerNews,populerArticle}) {

  return (
    <div className="">
      <Head>
        <title>EC BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />  
      </Head>
      <>
      <Carousel posts={posts} />
      <Section posts={posts} pNews={populerNews} pArticle = {populerArticle} />
      </>
      
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const { req, params } = context;

  const postsResponse = await axios.get(`${process.env.NEXT_PUBLIC_url}content`);
  const posts = postsResponse.data.reverse(); // Diziyi tersine çevir

  const populerNewsResponse = await axios.get("https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=a8ae07b7778c4e50aab671e9a3afc737")
  const populerArtıcle = await axios.get("https://newsapi.org/v2/everything?domains=wsj.com&apiKey=a8ae07b7778c4e50aab671e9a3afc737")

  return {
    props: {
      posts: posts ? posts : null,
      populerNews: populerNewsResponse ? populerNewsResponse.data : null,
      populerArticle:populerArtıcle ? populerArtıcle.data : null,
    },
  };
};
